services:
  node-exporter-1:
    image: prom/node-exporter:latest
    ports:
      - 8081:8081
    command: ["--web.listen-address", "0.0.0.0:8081"]

  node-exporter-2:
    image: prom/node-exporter:latest
    ports:
      - 8082:8082
    command: ["--web.listen-address", "0.0.0.0:8082"]

  node-exporter-3:
    image: prom/node-exporter:latest
    ports:
      - 8083:8083
    command: ["--web.listen-address", "0.0.0.0:8083"]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
