services:
  go-exporter:
    build:
      context: ./
    ports:
      - 8081:8081

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
